artboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('publicaciones/',include('publicaciones.urls') ),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publicaciones/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path("inicio/", views.inicio, name="inicio"),
    path("sesion/",LoginView.as_view(template_name="publicaciones/iniciar_sesion.html"),name="inicioSesion",),
    path("perfil/", views.perfil, name="perfil"),
    path("registro/", views.registro, name="registro"),
    path("registro_exitoso/", views.registro_exitoso, name="registro_exitoso"),
    path("restablecer_contraseña/",auth_views.PasswordResetView.as_view(template_name="publicaciones/restablecer_contraseña.html",),
        name="restablecer_contraseña",
    ),
    path(
        "restablecer_enviado/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="publicaciones/restablecer_enviado.html"
        ),
        name="password_reset_done",
    ),
    path(
        "restablecer_confirmar/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="publicaciones/restablecer_confirmar.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "restablecer_completo/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("cerrar_sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path('perfil/', views.ver_perfil, name='perfil'),
    path('subir_foto/', views.subir_foto, name='subir_foto'),
    path('publicacion/<int:pk>/', views.detalle_publicacion, name='detalle_publicacion'),
    path('publicacion/<int:pk>/comentario/', views.crear_comentario, name='crear_comentario'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('publicacion/<int:publicacion_id>/like/', views.like_publicacion, name='like-publicacion'),
    path('publicaciones/<int:pk>/eliminar/', views.eliminar_publicacion, name='eliminar-publicacion'),
    path('modificar_contraseña/',login_required(views.ChangePasswordView.as_view(),login_url="/publicaciones/sesion/"),name='modificar_contraseña'),
]

publicaciones/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from PIL import Image



# Create your models here.






class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to="perfil",default='default.jpg')
    def __str__(self):
        return f"{self.usuario.username}"
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.foto_perfil.path) # Open image

        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.foto_perfil.path) # Save it again and override the larger image


class Publicacion(models.Model):
    idPublicacion = models.AutoField(primary_key=True, verbose_name="Codigo Publicacion")
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=500)
    fechaPublicacion = models.DateField(auto_now_add=True)
    estatus = models.CharField(max_length=50)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE, verbose_name="Usuario")
    Imagen = models.ImageField(upload_to="publicaciones", null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    def total_likes(self):
        return self.likes.count()
    def __str__(self):
        return f"{self.titulo}"

class Imagen(models.Model):
    idImagen = models.AutoField(primary_key=True, verbose_name="Codigo Imagen")
    idPublicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, verbose_name="Id publicacion")
    nombre = models.TextField(max_length=20)
    archivo = models.CharField(max_length=20)


class Comentario(models.Model):
    idComentario = models.AutoField(primary_key=True, verbose_name="Codigo Comentario")
    idPublicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, verbose_name="Id publicacion")
    comentario = models.TextField(max_length=500)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE, verbose_name="Usuario")
    fechaCreacion = models.DateField(auto_now_add=True)






#class Like(models.Model):
  #  idLike = models.AutoField(primary_key=True, verbose_name="Codigo Like")
   # idPublicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, verbose_name="Id publicacion")
    #usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE, verbose_name="Usuario")

publicaciones/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Publicacion, Comentario, Perfil
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label="nombre de usuario", min_length=4, max_length=150,required=True)
    email = forms.EmailField(label="correo electrónico",required=True   )
    password1 = forms.CharField(label="contraseña", widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label="confirma tu contraseña", widget=forms.PasswordInput,
        required=True
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        help_texts = {k: "" for k in fields}

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        # Verificar si el nombre de usuario ya está registrado
        if User.objects.filter(username=username).exists():
            self.add_error("username", "El nombre de usuario ya está registrado. Por favor, elija otro.")
            

        # Verificar si el correo electrónico ya está registrado
        if User.objects.filter(email=email).exists():
            raise ValidationError("El correo electrónico ya está registrado. Por favor, utilice otro.")


        if  password1 != password2:
            self.add_error("password1","Las contraseñas no coinciden") 
        
        
        if "@" in username:
            self.add_error("username","No puede contener el caracter @ ")
        
        return cleaned_data
    
    


        

    
    


class PublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        exclude = ["usuario"]

        fields = ["titulo", "descripcion", "estatus", "usuario", "Imagen"]


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ["comentario"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ["foto_perfil"]

publicaciones/views.py
from http.client import HTTPResponse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect,get_object_or_404
from .models import *
from django.contrib import messages
from .forms import ComentarioForm, CustomUserCreationForm, PublicacionForm,ProfileForm
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required 
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView    
from django.contrib.messages.views import SuccessMessageMixin 
from django.utils.decorators import method_decorator



# Create your views here.

def inicio(request):
    publicaciones = Publicacion.objects.order_by("-fechaPublicacion")
    return render(request, 'publicaciones/inicio.html', {'publicaciones': publicaciones})

    publicacion = Publicacion.objects.get(idPublicacion=pk)

    if request.method == "POST":
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.idPublicacion = publicacion
            comentario.save()
            return redirect('detalle_publicacion', pk=pk)
    else:
        form = ComentarioForm()

    return render(request, "publicaciones/detalle_publicacion.html", {'publicacion': publicacion, 'form': form})


def detalle_publicacion(request, pk):
    publicacion = get_object_or_404(Publicacion, idPublicacion=pk)

    if request.method == 'POST':
        if request.user.is_authenticated:
            if request.user in publicacion.likes.all():
                # El usuario ya dio like, lo quitamos
                publicacion.likes.remove(request.user)
            else:
                # El usuario no ha dado like, lo agregamos
                publicacion.likes.add(request.user)
        else:
            # El usuario no está autenticado, redirigir a la página de inicio de sesión
            return redirect('inicioSesion')

    comentarios = Comentario.objects.filter(idPublicacion=publicacion)

    return render(request, "publicaciones/detalle_publicacion.html", {
        'publicacion': publicacion,
        'comentarios': comentarios,
    })

@login_required(login_url="/publicaciones/sesion/")
def like_publicacion(request, publicacion_id):
    publicacion = get_object_or_404(Publicacion, idPublicacion=publicacion_id)

    if request.method == 'POST':
        if request.user.is_authenticated:
            if request.user in publicacion.likes.all():
                # El usuario ya dio like, lo quitamos
                publicacion.likes.remove(request.user)
            else:
                # El usuario no ha dado like, lo agregamos
                publicacion.likes.add(request.user)
        else:
            # El usuario no está autenticado, redirigir a la página de inicio de sesión
            return redirect('inicioSesion')

    return redirect('detalle_publicacion', pk=publicacion_id)



@login_required(login_url="/publicaciones/sesion/")
def crear_comentario(request, pk):
    publicacion = get_object_or_404(Publicacion, idPublicacion=pk)

    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.usuario = request.user
            comentario.idPublicacion = publicacion
            comentario.save()
    return redirect('detalle_publicacion', pk=publicacion.idPublicacion)



@login_required(login_url="/publicaciones/sesion/")
def editar_perfil(request):
    if request.method =='POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.perfil)
        if form.is_valid():
            form.save()
            return redirect('perfil')
    else:
        form = ProfileForm(instance=request.user.perfil)
    return render(request, "publicaciones/editar_perfil.html", {'form': form})
    

    

@login_required(login_url="/publicaciones/sesion/")
def perfil(request):
    return render(request, "publicaciones/perfil.html")



def vista_inicio(request):
    Publicaciones = Publicacion.objects.all().order_by("fechaPublicacion")
    contexto = {
        "publicaciones": Publicaciones,
    }
    return render(request, "publicaciones/inicio.html", contexto)


def registro(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid(): 
            user = form.save() 
            login(request, user)
            return redirect("inicio")
        else:
            return render(request, "publicaciones/registro.html", {"form": form})
    else:
        form = CustomUserCreationForm()
    return render(request, "publicaciones/registro.html", {"form": form})


def registro_exitoso(request):
    return render(request, "publicaciones/registro_exitoso.html")

@login_required(login_url="/publicaciones/sesion/")
def subir_foto(request):
    if request.method == "POST":
        form = PublicacionForm(request.POST, request.FILES)
        if form.is_valid():
            publicacion = form.save(commit=False)
            publicacion.usuario = request.user
            publicacion.save()
            return redirect("inicio")
    else:
        form = PublicacionForm(initial={'usuario': request.user})

    contexto = {"form": form}
    return render(request, "publicaciones/subir_foto.html", contexto)


def cerrar_sesion(request):
    logout(request)
    return redirect("inicio")


@login_required(login_url="/publicaciones/sesion/")
def ver_perfil(request):



    usuario = request.user
    contexto = {
        "usuario": usuario,
    }
    return (render(request, "publicaciones/perfil.html", contexto),)

@login_required(login_url="/publicaciones/sesion/")
def eliminar_publicacion(request, pk):  
   

    publicacion = get_object_or_404(Publicacion, idPublicacion=pk)
    
    if request.method == 'POST':
        publicacion.delete()
        return redirect('inicio')  # Redirige a la página de inicio después de eliminar la publicación
    
    return render(request, 'publicaciones/eliminar_publicacion.html', {'publicacion': publicacion})


#def eliminar_comentario(request, pk):
    # Obtener el comentario que se desea eliminar
    comentario = get_object_or_404(Comentario, id=pk)
    
    # Verificar si el usuario tiene permisos para eliminar el comentario
    if request.user.is_superuser:
        # Eliminar el comentario
        comentario.delete()
    
    # Redireccionar a la página de detalle de la publicación o a otra página según tus necesidades
    return redirect('detalle-publicacion', publicacion_id=comentario.publicacion.idPublicacion)


#def modificar_contraseña(request):
    if request.method == 'POST':
        contraseña_actual = request.POST.get('current-password')
        nueva_contraseña = request.POST.get('new-password')
        confirmar_contraseña = request.POST.get('confirm-password')

        # Verificar si la contraseña actual coincide con la del usuario autenticado
        if request.user.check_password(contraseña_actual):
            # Verificar si la nueva contraseña y la confirmación coinciden
            if nueva_contraseña == confirmar_contraseña:
                # Cambiar la contraseña del usuario
                request.user.set_password(nueva_contraseña)
                request.user.save()

                messages.success(request, 'Contraseña modificada exitosamente.')
                return redirect('modificar_contraseña')
            else:
                messages.error(request, 'La nueva contraseña y la confirmación no coinciden.')
        else:
            messages.error(request, 'La contraseña actual es incorrecta.')

    return render(request, 'publicaciones/modificar_contraseña.html')


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):

    template_name= 'publicaciones/modificar_contraseña.html'
    success_message = 'cambiaste de contraseña'
    success_url = reverse_lazy("perfil")



    

publicaciones/templates/publicaciones/iniciar_sesion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Inicio de Sesión</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'publicaciones/css/detalle_login.css' %}">   
   <style>

    .img-fluid{
      width: 100px;
      height: 100px;
      margin: 0 auto;
      display: block;
    }
   </style>

  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <h1 class="text-center mb-4">Iniciar Sesión</h1>
          <a href={% url 'inicio' %}>
            <img  id ="imagen" src="{% static 'publicaciones/img/logo.png' %}" alt="Logo" class="img-fluid mb-4" />
          </a>
          <form class="form-signin" method="POST">
            {% csrf_token %}  
            <div class="mb-3">
              <label for="id_username" class="form-label"
                >Nombre de usuario:</label
              >
              <input
                type="text"
                class="form-control"
                name="username"
                autofocus=""
                autocapitalize="none"
                autocomplete="username"
                maxlength="150"
                required=""
                id="id_username"
              />
            </div>
            <div class="mb-3">
              <label for="id_password" class="form-label">Contraseña:</label>
              <input
                type="password"
                class="form-control"
                name="password"
                autocomplete="current-password"
                required=""
                id="id_password"
              />
            </div>
            <a href="{% url 'restablecer_contraseña' %}"> ¿Olvidaste tu contraseña?</a>
            <div class="text-center">
              <button class="btn btn-primary" type="submit">Entrar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

publicaciones/templates/publicaciones/inicio.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link
      rel="stylesheet"
      href="{% static 'publicaciones/css/detalle_inicio.css' %}"
    />
    
  </head>
  <body>
    <header
      class="navbar navbar-expand-md navbar-dark d-print-none bg-dark text-white px-4"
    >
      <h1
        class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3"
      >
        <a href="#" class="text-decoration-none text-white">
          <img
            src="{% static 'publicaciones/img/logo.png' %}"
            alt=""
            class="navbar-brand-image"
            width="32"
            height="32"
          />
          ARTBOARD
        </a>
      </h1>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbar-menu"
        aria-controls="navbar-menu"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div
        class="collapse navbar-collapse justify-content-end"
        id="navbar-menu"
      >
        {% if user.is_authenticated %}
        <div class="text-end">
          <div class="dropdown">
            <button
              class="btn btn-secondary dropdown-toggle me-5"
              type="button"
              id="userDropdown"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              {{ user.username }}
            </button>
            <ul class="dropdown-menu" aria-labelledby="userDropdown">
              <li>
                <a class="dropdown-item" href="{% url 'perfil'%}">Perfil</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'subir_foto'%}"
                  >Subir foto</a
                >
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="{% url 'cerrar_sesion'%}"
                  >Cerrar Sesión</a
                >
              </li>
            </ul>
          </div>
        </div>
        {% else %}
        <div class="text-end">
          <a href="{% url 'inicioSesion' %}">
            <button type="button" class="btn btn-outline-primary me-2">
              Iniciar Sesión
            </button>
          </a>
          <a href="{% url 'registro' %}">
            <button type="button" class="btn btn-primary">Registrarse</button>
          </a>
        </div>

        {% endif %}
      </div>
    </header>

    <div class="masonry">
      {% for publicacion in publicaciones %}
      <div class="item">
        <a href="{% url 'detalle_publicacion' publicacion.idPublicacion %}">
          <img src="{{ publicacion.Imagen.url }}" alt="Foto" />
        </a>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

publicaciones/templates/publicaciones/modificar_contraseña.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'publicaciones/css/modificar_contraseña.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
    </script>
    <link rel="stylesheet" href="{% static 'publicaciones/css/modificar_contraseña.css' %}">
  


</head>
</body>
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h3 class="font-weight-light my-4 text-center">MODIFICAR CONTRASEÑA</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_old_password">Contraseña Antigua</label>
                                            <input type="password" name="old_password" autocomplete="new-password"
                                                   class="form-control" required id="id_old_password"
                                                   placeholder="Ingresa Nueva Contraseña"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password1">Nueva Contraseña</label>
                                            <input type="password" name="new_password1" autocomplete="new-password"
                                                   class="form-control" required id="id_new_password1"
                                                   placeholder="Ingresa Nueva Contraseña"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password2">Confirmar Nueva Contraseña</label>
                                            <input type="password" name="new_password2" autocomplete="new-password"
                                                   required id="id_new_password2" class="form-control"
                                                   placeholder="Confirmar Nueva Contraseña"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-3 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark" id="reset">Modificar Contraseña</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>











</body>

</html>

publicaciones/templates/publicaciones/subir_foto.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Formulario de Subida de Fotos</title>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <link rel="stylesheet" href="{% static 'publicaciones/css/subir_foto.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<style> 
  h2{
    text-align: center;
    margin-top: 30px;
}
</style>
</head>

<body>
  <header class="navbar navbar-expand-md navbar-dark d-print-none bg-dark text-white px-4">
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      <a href="{% url 'inicio'%}" class="text-decoration-none text-white">
        <img src="{% static 'publicaciones/img/logo.png' %}" alt="Tabler" class="navbar-brand-image" width="32" height="32">
        ARTBOARD
      </a>
    </h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbar-menu">
      <div class="text-end">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle me-5" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </button>
          <ul class="dropdown-menu" aria-labelledby="userDropdown">
            <li><a class="dropdown-item" href="{% url 'perfil'%}">Perfil</a></li>
            <li><a class="dropdown-item" href="{% url 'subir_foto'%}">Subir foto</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'cerrar_sesion' %}">Cerrar Sesión</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
<h2>SUBIR FOTO</h2>
  <form method="post" enctype="multipart/form-data" class="mt-4">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_titulo" class="form-label">Título:</label>
      <input type="text" name="titulo" class="form-control" maxlength="50" required="" id="id_titulo">
    </div>

    <div class="mb-3">
      <label for="id_descripcion" class="form-label">Descripción:</label>
      <textarea name="descripcion" class="form-control" cols="40" rows="5" maxlength="500" required="" id="id_descripcion"></textarea>
    </div>

    <div class="mb-3">
      <label for="id_estatus" class="form-label">Estatus:</label>
      <input type="text" name="estatus" class="form-control" maxlength="50" required="" id="id_estatus">
    </div>




    <div class="mb-3">
      <label for="id_Imagen" class="form-label">Imagen:</label>
      <input type="file" name="Imagen" accept="image/*" class="form-control" id="id_Imagen">
    </div>

    <button type="submit" class="btn btn-primary">Subir foto</button>
  </form>
</body>
</html>